wallpaper {
    monitor = DP-2
    path = ~/.config/wallpapers/12.png
}

wallpaper {
    monitor =
    path = ~/.config/wallpapers/dark-waves.jpg
}

wallpaper {
    monitor = DP-3
    path = ~/.config/wallpapers/8.png
}
