wallpaper {
    monitor = DP-2
    path = ~/.config/wallpapers/catppuccin/12.png
}

wallpaper {
    monitor =
    path = ~/.config/wallpapers/catppuccin/Zephyr_5760x2880.png
}
    
wallpaper {
    monitor = DP-3
    path = ~/.config/wallpapers/catppuccin/8.png
}
